# === 1. CONFIGURAÇÕES DO BANCO DE DADOS H2 ===
spring.datasource.url=jdbc:h2:mem:loopidb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true

# Habilita o painel visual do H2 no navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# === 2. INTEGRAÇÕES (MAPBOX) ===
# O Spring vai buscar o valor real dentro do seu IntelliJ
mapbox.token=${MAPBOX_TOKEN}
