spring.application.name=loopi

spring.jpa.hibernate.ddl-auto=validate

spring.datasource.url=jdbc:mysql://localhost:3306/20261_prjint4_manha_loopi
spring.datasource.username=20261_prjint4_manha
spring.datasource.password=senac@12938

spring.jpa.show-sql=true

server.port=8080
